version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_NAME: "${POSTGRES_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432